### ISSUE TITLE
Only Users and Applications were migrated; nothing else mas migrated

### ISSUE THREAD

**Issue by GrayCygnus** [chirpstack/chirpstack-v3-to-v4#10]
Hello guys, hope everything is going well.

I'm migrating from 3 to 4, and tested this tool as per suggestion on https://www.chirpstack.io/docs/v3-v4-migration.html#data-migration 

I have my v4 up and running, DB created etc. When I ran the command I see that my users and applications were correctly migrated (All applications on my v3 are there, and the same user and credentials I used on v3 worked ok on v4).

However... nothing else was migrated :/ no profiles, no gateways and most sadly, no devices (only applications but not the devices that were inside that app).

Any guidance on this or any suggestions I can do to check and debug this situation? I'd like to avoid manually entering everything again, as we had 100s of devices.

Here's a screenshot of the output I get when running the command. Another relevant (?) detail is that my v3 server was Dockerized, as well as the v4 I'm configuring now. Other detail is that I have a chirpstack-packet-multiplexer running, but I managed the ports correctly (multiplex on 1700, gw-bridge I moved to 1701).

![Screenshot from 2023-07-28 17-13-55](https://github.com/chirpstack/chirpstack-v3-to-v4/assets/7274943/470327d1-0291-44fb-816d-afb995e12cbb)

Thanks,
Mike

**Comment by brocaar** [comment]
Well I see one big panic that is probably explaining your issue:

> dial tcp: lookup redis on 127.0.0.53:53: server misbehaving

This means that the host `redis` can not be resolved to an IP address (the DNS lookup fails).

**Comment by GrayCygnus** [comment]
Thanks for the reply @brocaar any idea where I could start hunting this down? Something I should edit or do to the v3-to-v4 script (I downloaded and used it as-is)?

Or is it on the docker part? The redis part on the docker-compose of v4 I left it as it is. On my v3 I also never "touched" it. The only difference I see now is that v3 was redis:5-alpine and now it is redis:7-alpine.

I'll check and try things and report here if I find something

**Comment by brocaar** [comment]
If you are running the migration tool outside of Docker, then you might want to update the configuration used by the migration tool. E.g. it tries to use `redis` as hostname to connect to Redis, but is this correct?

If you have two Docker Compose environments (v3 + v4), then you might want to expose these ports to the Docker host and use the Docker host IP + port instead of `redis` (which would work only if you are within a Compose environment).

**Comment by GrayCygnus** [comment]
Thanks @brocaar I will try those things. Yes, I have both my v3 and v4 Dockerized, so will try things like exposing the dockerip+redis port etc.

>If you are running the migration tool outside of Docker, then you might want to update the configuration used by the migration tool. E.g. it tries to use redis as hostname to connect to Redis, but is this correct?

How can I update the configuration used by the migration tool? 

Is this an option/flag on the migration script? Or by this you mean that I should try to "update" some of the chirpstack config files (v3, v4?) so that the "redis" part is explicit on IP and Port?

Thanks, I will inform what I find or when/if I make it.

Cheers,
Mike

**Comment by GrayCygnus** [comment]
Or, perhaps more clearly, why that "127.0.0.53:53"? I have nothing on such port nor IP. Redis "standard" port is 6379 and the docker instances have an ip (172.something). How can I indicate to the migration tool to look there and not on 127.0.0.53:53?

Perhaps I'm missing something from the documentation or manual

**Comment by brocaar** [comment]
Port 53 is DNS. I'm closing this issue as it is related to your configuration / setup. There is nothing I can fix in the code to resolve this issue.
