### ISSUE TITLE
`enabled_class` is wrongly migrated if sensor was not yet activated before in v3

### ISSUE THREAD

**Issue by gbrehmer** [chirpstack/chirpstack-v3-to-v4#11]
in this case `device.Mode` column is empty and such values produces `Unexpected DeviceClass` errors after migration to chirpstack v4, because `enabled_class` has not a valid value (empty string) 

In our case it seems to be enough to set `enabled_class` correctly on those sensors.

**Comment by brocaar** [comment]
Thanks for reporting :+1: The above commit should fix this. Note that on OTAA in v4, this value is automatically (re)set.

**Comment by augusthjerrild** [comment]
I'm facing the same issue.

How I do it:

1. I'm cloning this repo from the latest release tag (v4.0.6)
2. Running the "make" command
3. Running ./chirpstack-v3-to-v4 with the --as-config-file, --cs-config-file and the --ns-config-file flags.
4. Everything seems to work based on the logs from the terminal.

As an further update: When I look into my chirpstack postgres DB, enabled_class is just one space char..
So it looks like the check for an empty string doesn't catch it, but when I change the check for an " " (a space char), then it works..

Am I doing something wrong here? :-/
