### ISSUE TITLE
chirpstack api for csharp

### ISSUE THREAD

**Issue by kasen99** [chirpstack/chirpstack-v3-to-v4#12]
Hello! Sir! 
I need to create a new SCADA project because I want to present a good interface to customers, which includes images and animations in industrial scenarios. This is more user-friendly to operate, and compared to the web approach developed by Golang, this undoubtedly has great advantages. Golang lacks graphic expression. I found that the chirpstack API does not have the csharp version of the gRPC method, which makes it even more difficult for me to choose which path to use to do this. Excuse me, do you have any gRPC methods for csharp that can be published? Thank you!

**Comment by brocaar** [comment]
Please see: https://github.com/chirpstack/chirpstack/tree/master/api/csharp.

**Comment by kasen99** [comment]
thank you very much!
