### ISSUE TITLE
device profile errors after migration

### ISSUE THREAD

**Issue by bzuelly** [chirpstack/chirpstack-v3-to-v4#13]
see https://forum.chirpstack.io/t/error-unexpected-revision-v3-to-v4-tool/17461 for additional details.  

I'm using redis 7 as well as postgres 15 in a ha setup with nginx as a proxy.  I dont recall seeing this issue when i ran the migration tool earlier this year.   I have looked at things like changing the codec and spaces/dashes in the device profile names in case that was an issue.  In my case, clicking on "device profiles" in my first org is completely blank, but if i click on a profile from a device it works.  looking at the commit history, maybe its related to recent db schema changes?

--Bryan

**Comment by bzuelly** [comment]
I found the problem and fixed it manually.  I had 89 records with a blank value in the "Mode" column of the device table in the network server database on the chirpstack v3 side. 
 https://github.com/chirpstack/chirpstack-v3-to-v4/blob/master/main.go#L1146 looks to be placing an "A" there, but I'm not sure its working.

**Comment by brocaar** [comment]
I have just published v4.0.6, this should fix the issue.
