### ISSUE TITLE
panic: pq: null value in column "is_relay" of relation "device_profile" violates not-null constraint

### ISSUE THREAD

**Issue by AngeLinuX99** [chirpstack/chirpstack-v3-to-v4#14]
Hi
I'm trying to upgrade on different docker containers using last version of chirpstack-v3-to-v4. It doesn't end because this error Can somebody help me to fix this issue ?

debian@docker4:~$ ./chirpstack-v3-to-v4 --cs-config-file /home/debian/cs/configuration/chirpstack/chirpstack.toml --as-config-file /home/debian/eu868/configuration/chirpstack-application-server/chirpstack-application-server.toml --ns-config-file /home/debian/eu868/configuration/chirpstack-network-server/chirpstack-network-server.toml
2023/09/25 19:44:34 Reading ChirpStack configuration file: /home/debian/cs/configuration/chirpstack/chirpstack.toml
2023/09/25 19:44:34 Reading AS configuration file: /home/debian/eu868/configuration/chirpstack-application-server/chirpstack-application-server.toml
2023/09/25 19:44:34 Deleting users and tenants from target database
2023/09/25 19:44:34 Migrating users
2023/09/25 19:44:34 Migrating organizations
2023/09/25 19:44:34 Migrating organization users
2023/09/25 19:44:34 Migrating applications
2023/09/25 19:44:34 Migrating application integrations
2023/09/25 19:44:34 Reading NS configuration file: /home/debian/eu868/configuration/chirpstack-network-server/chirpstack-network-server.toml
2023/09/25 19:44:34 Migrating gateways
2023/09/25 19:44:35 Migrating device-profiles
panic: pq: null value in column "is_relay" of relation "device_profile" violates not-null constraint

goroutine 1 [running]:
main.migrateDeviceProfiles()
	/chirpstack-v3-to-v4/main.go:1042 +0x97f
main.run(0xf32a80?, {0xa9afa7?, 0x6?, 0x6?})
	/chirpstack-v3-to-v4/main.go:114 +0x57a
github.com/spf13/cobra.(*Command).execute(0xf32a80, {0xc00018a010, 0x6, 0x6})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xf32a80)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/chirpstack-v3-to-v4/main.go:79 +0x25

**Comment by brocaar** [comment]
Please note that there is a strict relation between the v3 to v4 migration utility and the ChirpStack v4 version. It looks like you are using a migration version that didn't implement the relay feature in ChirpStack v4 yet.
