### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by gfnord** [chirpstack/chirpstack-v3-to-v4#16]
Hi everyone, 

The program is not running. I got the index out of range error. Any thoughts? Thanks.

loraserver:~/chirpstack-v3-to-v4# ./chirpstack-v3-to-v4 --cs-config-file /etc/chirpstack/chirpstack.toml --as-config-file /etc/chirpstack-application-server/chirpstack-application-server.toml --ns-config-file /etc/chirpstack-network-server/chirpstack-network-server.toml
2023/11/27 17:04:09 Reading ChirpStack configuration file: /etc/chirpstack/chirpstack.toml
2023/11/27 17:04:09 Reading AS configuration file: /etc/chirpstack-application-server/chirpstack-application-server.toml
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getRedisClient({{{0xc000128380, 0x57}}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, {0x0, 0x0}, ...}})
        /root/chirpstack-v3-to-v4/main.go:306 +0x265
main.run(0xc000172300?, {0xaa12cc?, 0x4?, 0xaa1168?})
        /root/chirpstack-v3-to-v4/main.go:126 +0x358
github.com/spf13/cobra.(*Command).execute(0xf83160, {0xc000024080, 0x6, 0x6})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xf83160)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /root/chirpstack-v3-to-v4/main.go:110 +0x1a

**Comment by brocaar** [comment]
This might be because you have your Redis configuration in the old format. If you change it to a list of servers in your TOML configuration, the issue should be resolved. Example:

```toml
[redis]

# Server address or addresses.
#
# Set multiple addresses when connecting to a cluster.
servers=[
  "localhost:6379",
]
```
