### ISSUE TITLE
Migration error..? - issue with column data types

### ISSUE THREAD

**Issue by JozefRuta** [chirpstack/chirpstack-v3-to-v4#17]
Hi there,
I am trying to migrate V3 chirpstack to newest one, but unfortunately I coudn't do it. It served by docker compose, in containers.
Here is my docker-compose.yml :
version: "3.5"

services: 
  #**********************************************************************************
  #*    chirpstack network server
  #**********************************************************************************
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3.16.8
    container_name: chirp-network-server
    restart: always
    ports:
      - 8003:8003
    volumes:
      - /etc/soitron/configs/chirpstack-network-server:/etc/chirpstack-network-server
      - /etc/soitron/configs/chirpstack-network-server/chirpstack-network-server.log
    depends_on:
      - postgresql
      - mosquitto
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  #**********************************************************************************
  #*    chirpstack application server  
  #**********************************************************************************
  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3.17.9
    container_name: chirp-application-server
    restart: always
    ports:
      - 8880:8080
      - 8001:8001
    volumes:
      - /etc/soitron/configs/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
      
  #**********************************************************************************
  #*    chirpstack gateway  bridge
  #**********************************************************************************
  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3.14.8
    container_name: chirp-gateway-bridge
    restart: always
    ports:
      - 1700:1700/udp
    volumes:
      - /etc/soitron/configs/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
      
  #**********************************************************************************
  #*    redis
  #**********************************************************************************    
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    volumes:
      - /var/lib/soitron/redisdata:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  
  #**********************************************************************************
  #*    Mosquitto
  #**********************************************************************************     
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes: 
      - /etc/soitron/configs/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
              
  #**********************************************************************************
  #*    Postgresql   
  #**********************************************************************************
  
  
  postgresql:
    image: postgres:14-alpine3.15 
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - /var/lib/soitron/postgreSQL/data:/var/lib/postgresql/data
      - /etc/soitron/configs/postgresql/initdb:/docker-entrypoint-initdb.d 
    environment:
      POSTGRES_PASSWORD: xxxxxx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  postgres-new:
    image: postgres:14-alpine
    ports:
      - 127.0.0.1:5444:5432
    container_name: postgres-new
    restart: unless-stopped
    volumes:
      - /etc/soitron/configs/postgres-new/initdb:/docker-entrypoint-initdb.d
      - /var/lib/soitron/postgres-new/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
     

  chirpstack4:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - /etc/soitron/configs/chirpstack:/etc/chirpstack
      - /etc/soitron/configs/chirpstack/chirpstack.log
      - /etc/soitron/lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres-new
      - redis7
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres-new
    ports:
      - 8888:8080
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

        
  #**********************************************************************************
  #*    redis
  #**********************************************************************************    
  redis7:
    image: redis:7-alpine
    container_name: redis7
    restart: unless-stopped
    volumes:
      - /var/lib/soitron/redisnew:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

Firstly I received this error:
2023/11/30 06:17:20 Select users errordial tcp: lookup postgresql on 127.0.0.53:53: server misbehaving
And later
errors like this related to integrations and other some missing collumns
Exec application integrations statement errorpq: invalid input syntax for type uuid: "InfluxDb"
I tried to remove unneccessary integrations and add some collumns to ne Chirp V4 but, I find out this is because old V3 use different data types than new V4. So I stucked here.
Then I try to change some .toml and also docker-compose.yml somehow. But I am back at the start with first error "127.0.0.53:53: server misbehaving".
I have no other ideas what to do or change. I am writing here because I need some help.
Here is toml files:
[chirpstack-application-server.txt](https://github.com/chirpstack/chirpstack-v3-to-v4/files/13529948/chirpstack-application-server.txt)
[chirpstack-network-server.txt](https://github.com/chirpstack/chirpstack-v3-to-v4/files/13529949/chirpstack-network-server.txt)
[chirpstack.txt](https://github.com/chirpstack/chirpstack-v3-to-v4/files/13529950/chirpstack.txt)

Thank you for every idea ;)

**Comment by brocaar** [comment]
> 2023/11/30 06:17:20 Select users errordial tcp: lookup postgresql on 127.0.0.53:53: server misbehaving

This is a configuration issue. E.g. the hostname can't be resoved from where you run the migration tool.

> Exec application integrations statement errorpq: invalid input syntax for type uuid: "InfluxDb"

Fixed by the above commit.

**Comment by JozefRuta** [comment]
It looks like there is more issues with other columns
Or I did some mistake

root@Running-v3-Chirpstack:/home/soitron# ./chirpstack-v3-to-v4 --cs-config-file /etc/soitron/configs/chirpstack/chirpstack.toml-local --as-config-file /etc/soitron/configs/chirpstack-application-server/chirpstack-application-server.toml-local --ns-config-file /etc/soitron/configs/chirpstack-network-server/chirpstack-network-server.toml-local
2023/12/08 19:27:59 Reading ChirpStack configuration file: /etc/soitron/configs/chirpstack/chirpstack.toml-local
2023/12/08 19:27:59 Reading AS configuration file: /etc/soitron/configs/chirpstack-application-server/chirpstack-application-server.toml-local
2023/12/08 19:27:59 Deleting users and tenants from target database
2023/12/08 19:27:59 Migrating users
2023/12/08 19:27:59 Migrating organizations
panic: pq: null value in column "tags" of relation "tenant" violates not-null constraint

goroutine 1 [running]:
main.migrateOrganizations()
        /chirpstack-v3-to-v4/main.go:318 +0x373
main.run(0xf33a80?, {0xa9afa7?, 0x6?, 0x6?})
        /chirpstack-v3-to-v4/main.go:101 +0x37f
github.com/spf13/cobra.(*Command).execute(0xf33a80, {0xc00001e080, 0x6, 0x6})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xf33a80)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /chirpstack-v3-to-v4/main.go:79 +0x25
root@Running-v3-Chirpstack:/home/soitron#

**Comment by JozefRuta** [comment]
If I remove one I get another:
root@Running-v3-Chirpstack:/home/soitron/chirpstack-v3-to-v4# ./chirpstack-v3-to-v4 \
> --cs-config-file /etc/soitron/configs/chirpstack/chirpstack.toml-local \
> --as-config-file /etc/soitron/configs/chirpstack-application-server/chirpstack-application-server.toml-local \
> --ns-config-file /etc/soitron/configs/chirpstack-network-server/chirpstack-network-server.toml-local
2023/12/08 20:30:31 Reading ChirpStack configuration file: /etc/soitron/configs/chirpstack/chirpstack.toml-local
2023/12/08 20:30:31 Reading AS configuration file: /etc/soitron/configs/chirpstack-application-server/chirpstack-application-server.toml-local
2023/12/08 20:30:31 Start migration
2023/12/08 20:30:31 Migrating users
2023/12/08 20:30:31 Exec user statement errorpq: duplicate key value violates unique constraint "user_pkey"

**Comment by brocaar** [comment]
Which version of the v3 to v4 migration utility are you using? Are you
using the latest release from yesterday?

**Comment by JozefRuta** [comment]
Hi, 
I had version cloned 8.12 20:30
But to be sure I tried it again
![image](https://github.com/chirpstack/chirpstack-v3-to-v4/assets/65413551/b70612bb-c92d-4032-bdb3-11b20ae9e22f)
![image](https://github.com/chirpstack/chirpstack-v3-to-v4/assets/65413551/c469a6ce-16d3-490a-8d5f-d72ed7a1f0cc)
I couldn't find written version number anywhere.

**Comment by brocaar** [comment]
Please see:
https://github.com/chirpstack/chirpstack-v3-to-v4/releases/tag/v4.0.7.

**Comment by JozefRuta** [comment]
Hi, I downloaded your precompiled version and untar again. But I have the same error:
![image](https://github.com/chirpstack/chirpstack-v3-to-v4/assets/65413551/cb330786-568c-432d-8ef9-80796f59d7e7)

**Comment by brocaar** [comment]
> Duplicate key value violates unique constraint "user_pkey"

That means you try to migrate the same user twice, the DB constraint guarantees that an user only can exist once. Please see the `README`, if you want to overwrite / remove all data before re-running the migration you need to use `--drop-tenants-and-users`.

The latest version introduces many new flags to make it easier to do partial migrations.

**Comment by JozefRuta** [comment]
Hi,
I really appreciate your help 👍 
I have to remove DB volume of V4 postgres...compose up/down it wasn't enough. It is obvious because volume is outside of container and if tried to migrate many times before there was something partialy migrated.
Have a nice day!
