### ISSUE TITLE
enabled_class is wrongly migrated if sensor was not yet activated before in v3

### ISSUE THREAD

**Issue by augusthjerrild** [chirpstack/chirpstack-v3-to-v4#18]
After a migration from v3 to v4, when I look into my chirpstack postgres DB for an IoT-device, enabled_class is just one space char.
So it looks like the check for an empty string doesn't catch it, since the string is not empty but " ". When I change the script myself to  check for an " " (a space char), then it works.

Can this fix be made in a new release :-)?
Thx for an awesome migration repo either way!

**Comment by brocaar** [comment]
Thanks, the above commit should fix this.
