### ISSUE TITLE
duplicate key value violates unique constraint "idx_user_email"

### ISSUE THREAD

**Issue by augusthjerrild** [chirpstack/chirpstack-v3-to-v4#19]
After I cloned the newest release, 4.0.7, i'm facing issues with the migration that I didn't face with v. 4.0.6. I'm using the exact same command.

When starting to migrating users, i'm facing this: "Exec user statement errorpq: duplicate key value violates unique constraint "idx_user_email""

The user in v3 is "admin".

If I try to use the "migrate-users=false" flag, I get this error instead: 

"Prepare tenant statement errorpq: column "tags" of relation "tenant" does not exist"

My organization in chirpstack V3 is "ChirpStack".

If I try to use the "migrate-tenants=false" flag i get this error instead:

"Prepare application statement errorpq: column "tags" of relation "application" does not exist".

Am I doing something wrong, or is this a new error after the release :-)?

**Comment by brocaar** [comment]
> "Prepare tenant statement errorpq: column "tags" of relation "tenant" does not exist"
> "Prepare application statement errorpq: column "tags" of relation "application" does not exist".

You are running an older ChirpStack v4 version. These fields were added in v4.6.0: https://www.chirpstack.io/docs/chirpstack/changelog.html#tenant-and-application-tags

If you update to the latest v4 version, you should no longer see this error.

**Comment by augusthjerrild** [comment]
I now updated to v.4.6.0, but I still get this error:
"Exec user statement errorpq: duplicate key value violates unique constraint "idx_user_email""
And now, if I run with --migrate-users=false (which i'm not sure is intended? At least it wasn't necessary in release 4.0.6), I get this error:
"Exec tenant users statement errorpq: insert or update on table "tenant_user" violates foreign key constraint "tenant_user_user_id_fkey"" :-)

**Comment by brocaar** [comment]
If you want the same behavior as before, use:

```
--drop-tenants-and-users               Drop tenants and users before migration
```

That is what the previous version was doing by default.

**Comment by augusthjerrild** [comment]
Amazing, thank you so much!
