### ISSUE TITLE
Execute device-queue-item statement errorpq: null value in column "is_encrypted" of relation "device_queue_item" violates not-null constraint

### ISSUE THREAD

**Issue by augusthjerrild** [chirpstack/chirpstack-v3-to-v4#20]
Hi!

Today I faced an error while migrating a project to Chirpstack V4.

The error was the following: 

"Execute device-queue-item statement errorpq: null value in column "is_encrypted" of relation "device_queue_item" violates not-null constraint"

As far as I can see, is_encrypted is a new row in the device_queue_item and is not_null. is_encrypted is not a part of the existing ns db. 

Am I missing something :-)?

**Comment by brocaar** [comment]
Fixed in v4.0.8. Thanks for reporting :+1:
