### ISSUE TITLE
Migrate between docker-compose stacks

### ISSUE THREAD

**Issue by AndreasW79** [chirpstack/chirpstack-v3-to-v4#7]
Hi there, 

anyone tried to migrate from an current Chirpstack 3 dockerstack to new Chirpstack 4 dockerstack?
Currently i merged both verions (3 and 4) into one stack with many services and linked the config files to the new
application service from Chirpstack 4... But as user nobody i cant execute the migration script, from outside the stack i cant reach the services /destinations inside the stack, for example the postgres host - currently i have not further ideas. Running the docker-compose file from this repo the image is created but i have no clue how to use it exactly maybe with docker run and some paths and options??

Thanks in advance.

**Comment by brocaar** [comment]
What I'm doing locally is to expose the Redis and PostgreSQL ports in the `docker-compose.yml` file for both the v3 and the v4 environment. Then I run the migration script outside Docker. This works well for me.

**Comment by AndreasW79** [comment]
Hi @brocaar,
thanks for your answer, this sounds good for me, will try it later today and give a feedback.

Best regards

**Comment by AndreasW79** [comment]
@brocaar - one more question, if i expose the ports, i have to use different ports for v3 (f.e. default port) and v4 (default port+1) but the hostnames and ports from the config files will just work inside the docker environment or do you add the names in the hosts file?? Or did i miss something and the script doesnt use the connection strings from the config files, or do you use different config files for migration with localhost as redis and postgreSQL?? What would be the best practice?

**Comment by AndreasW79** [comment]
Tested - worked for me.
